name: Local Deployment Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        pytest

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run tests
      run: |
        cd frontend
        npm test

  build-and-push:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker images
      run: |
        # Set variables for image names with GitHub Container Registry
        export FRONTEND_IMAGE=ghcr.io/${{ github.repository_owner }}/garazas-frontend:latest
        export BACKEND_IMAGE=ghcr.io/${{ github.repository_owner }}/garazas-backend:latest
        
        # Build the images
        docker build -t $FRONTEND_IMAGE ./frontend
        docker build -t $BACKEND_IMAGE ./backend
        
        # Push the images
        docker push $FRONTEND_IMAGE
        docker push $BACKEND_IMAGE
        
        # Create a deployment marker file
        echo "{\"commit\": \"${{ github.sha }}\", \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"frontend_image\": \"$FRONTEND_IMAGE\", \"backend_image\": \"$BACKEND_IMAGE\"}" > deployment.json
      
    - name: Upload deployment marker
      uses: actions/upload-artifact@v3
      with:
        name: deployment-info
        path: deployment.json
        
    # Optional: Trigger a webhook that your local machine listens to
    - name: Notify local server
      if: false  # Disabled by default - enable and configure when you set up a webhook receiver
      run: |
        curl -X POST https://your-local-machine-endpoint/deploy \
          -H "Content-Type: application/json" \
          -d "{\"commit\": \"${{ github.sha }}\", \"repository\": \"${{ github.repository }}\"}" 